sudo: true

language: node_js
node_js:
  - 9
  - 8
  - 7
  - 6
  - 5.1
  - 5
  - 4
  - 4.2
  - 4.1
  - 4.0
  - 0.12
  - iojs

env:
  global:
    - HTML_FOLDER="_site/"
    - HTML_EXCLUDES=""
    - STYLE_FOLDER="static/css"
    - CSS_FILES="static/css/style.css"
    - SCSS_FILES="static/css/style.scss"
    - CSS_EXCLUDES=""
    - JS_FOLDER="static/js/"
    - BASH_FILES="sample.sh"
    - MARKDOWN_FILES="_posts/*.markdown"
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # Speeds up htmlproof

cache:
  bundler: true
  pip: true
  directories:
    - node_modules
    - $HOME/.yarn-cache
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

before_install:
  - rvm install 2.2.0-dev

install:
  - bundle install --quiet
  - npm install --global yarn
  - yarn
  - sudo pip install --verbose -r requirements.txt
# - brew update && brew tap homebrew/dupes && brew install homebrew/dupes/tidy --HEAD

before_script:
  - cat Gemfile.lock

script:
  - echo "Build your files here"
# - jekyll build --profile

after_script:
  - echo "Run your linters on the files"
# - yarn run check-html -- $HTML_FOLDER
# - yarn run lint-html -- $HTML_FOLDER
# - yarn run lint-css -- $CSS_FILES # Requires config file
# - yarn run lint-scss -- $SCSS_FILES # Requires config file
# - jscs $JS_FOLDER # Requires config file
# - jshint $JS_FOLDER
# - yarn run lint-bash -- $BASH_FILES
# - yarn run lint-md -- $MARKDOWN_FILES  # Requires config file
# - yarn run test-js

matrix:
  allow_failures:
    - node_js: 5
    - node_js: 5.1
    - node_js: 4
    - node_js: 4.2
    - node_js: 4.1
    - node_js: 4.0
    - node_js: 0.12
    - node_js: iojs

notifications:
  email:
    on_success: change
    on_failure: always
