sudo: true

language: ruby
rvm:
  - 2.2.0-dev

env:
  global:
    - HTML_FOLDER="_site/"
    - HTML_EXCLUDES=""
    - STYLE_FOLDER="static/css"
    - CSS_FILES="static/css/style.css"
    - SCSS_FILES="static/css/style.scss"
    - CSS_EXCLUDES=""
    - JS_FOLDER="static/js/"
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # Speeds up htmlproof

install:
  - bundle install --verbose
  - npm install
  - sudo pip install --verbose -r requirements.txt
# - brew update && brew tap homebrew/dupes && brew install homebrew/dupes/tidy --HEAD

before_script:
  - cat Gemfile.lock

script:
  - echo "Build your files here"

after_script:
  - echo "Run your linters on the files"

notifications:
  email:
    on_success: change
    on_failure: always
